// Content for the standalone city/service landing pages listed in
// public/sitemap.xml. Each entry is deliberately distinct (not a
// find-replace template) — thin, near-duplicate city pages get
// filtered out of Google's index rather than ranking.
export interface CityPageData {
  path: string; // must match a <loc> in public/sitemap.xml
  title: string;
  description: string;
  h1: string;
  intro: string;
  servicesHeading: string;
  services: string[];
  areasHeading: string;
  areas: string;
  whyHeading: string;
  why: string;
}

export const CITY_PAGES: CityPageData[] = [
  {
    path: "/hvac-services/haldwani/",
    title: "HVAC Services in Haldwani | AC Installation & Repair | Climewave Engineers",
    description: "Expert HVAC installation, AC repair & annual maintenance in Haldwani, Kathgodam, Lalkuan & Bhimtal. 200+ systems installed across Kumaon. Free site visit.",
    h1: "HVAC Services in Haldwani",
    intro: "Climewave Engineers provides expert HVAC installation, AC repair, and annual maintenance services in Haldwani and surrounding areas including Lalkuan, Kathgodam, and Bhimtal. With over 200 systems installed across Kumaon, we are Haldwani's trusted HVAC partner.",
    servicesHeading: "Our Services in Haldwani",
    services: ["Split AC Installation & Repair", "Central AC Design & Installation", "Commercial HVAC Systems", "Annual Maintenance Contracts (AMC)", "VRF/VRV System Design"],
    areasHeading: "Areas We Serve in Haldwani",
    areas: "Haldwani, Kathgodam, Lalkuan, Ramnagar, Bhimtal, Nainital Road",
    whyHeading: "Why Choose Climewave in Haldwani?",
    why: "Our AI-powered HVAC calculator ensures you buy the right AC size for your room — saving you thousands on wrong purchases and 25–35% on monthly electricity bills vs standard split AC setups.",
  },
  {
    path: "/ac-repair/haldwani/",
    title: "AC Repair in Haldwani | Same-Day Service | Climewave Engineers",
    description: "Fast AC repair in Haldwani — gas refilling, compressor faults, no-cooling diagnosis, and AMC renewal. Same-day technician visits across Haldwani & Kathgodam.",
    h1: "AC Repair in Haldwani",
    intro: "When your split or central AC stops cooling in Haldwani's peak summer heat, waiting days for a technician isn't an option. Climewave Engineers runs a dedicated repair team covering Haldwani, Kathgodam, and Lalkuan with same-day visits for most fault categories.",
    servicesHeading: "Common Repairs We Handle",
    services: ["No-cooling & low-cooling diagnosis", "Refrigerant (gas) leak detection & refilling", "Compressor & PCB fault repair", "Noisy unit & water-leakage fixes", "AMC renewal & pre-summer servicing"],
    areasHeading: "Repair Coverage Area",
    areas: "Haldwani, Kathgodam, Lalkuan, Nainital Road, Bhimtal",
    whyHeading: "Why Book Repairs Through Climewave?",
    why: "Every repair technician is trained on the same BEE and ASHRAE standards our installation engineers use, so a \"quick fix\" doesn't quietly shorten your system's life — we diagnose the root cause, not just the symptom.",
  },
  {
    path: "/hvac-services/ramnagar/",
    title: "HVAC Services in Ramnagar | Resort & Home AC Systems | Climewave Engineers",
    description: "HVAC installation for homes, resorts & restaurants in Ramnagar near Corbett. Multi-zone VRF systems, split AC, and commercial cooling. Free site visit.",
    h1: "HVAC Services in Ramnagar",
    intro: "Ramnagar's mix of homes, resorts, and restaurants near Corbett National Park each have different cooling demands — a guest room needs quiet, consistent comfort, while a restaurant kitchen needs heavy-duty ventilation. Climewave Engineers designs HVAC systems around that difference rather than a one-size-fits-all install.",
    servicesHeading: "Our Services in Ramnagar",
    services: ["Multi-zone VRF/VRV for resorts & guesthouses", "Split & Central AC for residences", "Kitchen & restaurant ventilation systems", "Commercial HVAC for retail spaces", "Annual Maintenance Contracts (AMC)"],
    areasHeading: "Areas We Serve in Ramnagar",
    areas: "Ramnagar, Corbett, Kaladhungi, Dhikuli, Mohan",
    whyHeading: "Why Choose Climewave in Ramnagar?",
    why: "We've already delivered a multi-zone VRF installation for a resort & restaurant client in Ramnagar's Choi area, sized for variable seasonal occupancy — the kind of load planning a generic split-AC vendor typically skips.",
  },
  {
    path: "/ac-repair/ramnagar/",
    title: "AC Repair in Ramnagar | Homes, Resorts & Restaurants | Climewave Engineers",
    description: "AC & VRF repair in Ramnagar for homes, resorts and restaurants near Corbett. Compressor, gas refill, and cooling-coil fault repair with fast response.",
    h1: "AC Repair in Ramnagar",
    intro: "A resort or restaurant losing cooling in Ramnagar's tourist season means unhappy guests the same night — not next week. Climewave Engineers services both residential split units and larger VRF/VRV systems used by hospitality properties around Corbett.",
    servicesHeading: "Common Repairs We Handle",
    services: ["VRF/VRV outdoor & indoor unit faults", "Split AC gas refilling & compressor repair", "Cooling-coil cleaning & airflow restoration", "Emergency response for hospitality properties", "Seasonal pre-check before peak tourist months"],
    areasHeading: "Repair Coverage Area",
    areas: "Ramnagar, Corbett, Dhikuli, Kaladhungi",
    whyHeading: "Why Book Repairs Through Climewave?",
    why: "Because we design and install VRF systems ourselves, our repair technicians already understand multi-zone refrigerant circuits — not just single-split units — which matters when the fault is a shared outdoor compressor serving several rooms.",
  },
  {
    path: "/hvac-services/rudrapur/",
    title: "HVAC Services in Rudrapur | Industrial & Factory Cooling | Climewave Engineers",
    description: "Industrial HVAC and process cooling for Rudrapur's factories and warehouses, plus home & office AC installation. Precision temperature control, 24/7 monitoring.",
    h1: "HVAC Services in Rudrapur",
    intro: "Rudrapur's industrial belt runs factories and warehouses where temperature isn't just comfort — it's a process requirement. Climewave Engineers handles both that heavy-load industrial cooling and standard home/office AC installation across the city.",
    servicesHeading: "Our Services in Rudrapur",
    services: ["Industrial process cooling & precision temperature control", "Warehouse & factory ventilation systems", "24/7 performance monitoring for critical environments", "Office & commercial split/central AC", "Redundancy planning for production lines"],
    areasHeading: "Areas We Serve in Rudrapur",
    areas: "Rudrapur, Pantnagar, Gadarpur, Bazpur, Kichha",
    whyHeading: "Why Choose Climewave in Rudrapur?",
    why: "We've delivered a 22,000 sq ft precision-cooling installation for a Rudrapur factory holding 18±1°C with dual-redundant systems and real-time monitoring — the kind of spec industrial clients actually audit before sign-off.",
  },
  {
    path: "/hvac-services/kashipur/",
    title: "HVAC Services in Kashipur | AC Installation & Commercial Cooling | Climewave Engineers",
    description: "HVAC installation, AC repair and commercial cooling systems in Kashipur, Jaspur & Bazpur. Zone-by-zone planning for offices and retail spaces.",
    h1: "HVAC Services in Kashipur",
    intro: "From single-room split AC to zone-by-zone cooling for an entire office floor, Climewave Engineers plans Kashipur installations around actual usage patterns rather than selling the largest unit available.",
    servicesHeading: "Our Services in Kashipur",
    services: ["Residential split & central AC installation", "Zone-by-zone office & retail cooling", "Energy efficiency audits for existing systems", "AC repair & AMC renewal", "Smart thermostat integration"],
    areasHeading: "Areas We Serve in Kashipur",
    areas: "Kashipur, Jaspur, Bazpur, Thakurdwara, Kundeshwari",
    whyHeading: "Why Choose Climewave in Kashipur?",
    why: "Our free AI-powered BTU calculator runs before we quote anything — so a Kashipur homeowner or shop owner knows the right tonnage before spending a rupee, not after an oversized unit inflates the electricity bill.",
  },
  {
    path: "/hvac-services/khatima/",
    title: "HVAC Services in Khatima | AC Installation & Maintenance | Climewave Engineers",
    description: "AC installation, repair and maintenance in Khatima, Sitarganj & Nanakmatta. Split and central AC systems sized to your room with a free site visit.",
    h1: "HVAC Services in Khatima",
    intro: "Khatima's border-belt climate swings hard between summer heat and cooler winters, which makes correct AC sizing more important, not less — an oversized unit short-cycles and wastes power, an undersized one never actually cools the room. Climewave Engineers sizes every Khatima installation to the room, not the wall space available.",
    servicesHeading: "Our Services in Khatima",
    services: ["Split AC installation & repair", "Central AC for larger homes", "Annual Maintenance Contracts (AMC)", "Placement optimization for airflow coverage", "Filter & refrigerant servicing"],
    areasHeading: "Areas We Serve in Khatima",
    areas: "Khatima, Sitarganj, Nanakmatta, Tanakpur",
    whyHeading: "Why Choose Climewave in Khatima?",
    why: "Every quote includes our placement analysis — which wall gets the best airflow coverage for your specific room shape — a step most local installers skip entirely.",
  },
  {
    path: "/hvac-services/sitarganj/",
    title: "HVAC Services in Sitarganj | AC Installation & Repair | Climewave Engineers",
    description: "HVAC installation and AC repair in Sitarganj, Khatima & Dineshpur. Residential and small commercial systems with BEE-certified engineers.",
    h1: "HVAC Services in Sitarganj",
    intro: "Sitarganj's growing residential and small-commercial base needs installers who'll return for servicing, not just disappear after the sale. Climewave Engineers runs ongoing AMC coverage alongside new installations here.",
    servicesHeading: "Our Services in Sitarganj",
    services: ["Split AC installation & repair", "Small commercial & shop cooling systems", "Annual Maintenance Contracts (AMC)", "COP performance testing on existing units", "Emergency repair response"],
    areasHeading: "Areas We Serve in Sitarganj",
    areas: "Sitarganj, Khatima, Nanakmatta, Dineshpur",
    whyHeading: "Why Choose Climewave in Sitarganj?",
    why: "BEE and ASHRAE certified engineers handle every installation, and our COP performance testing means we can tell you objectively whether an aging unit is worth repairing or replacing — not just upsell a new one.",
  },
  {
    path: "/hvac-services/lalkuan/",
    title: "HVAC Services in Lalkuan | AC Installation Near Haldwani | Climewave Engineers",
    description: "AC installation and repair in Lalkuan and Bindukhatta, near Haldwani. Split and central AC systems with free site visit and AMC coverage.",
    h1: "HVAC Services in Lalkuan",
    intro: "Lalkuan sits close enough to our Haldwani base that response times for both installation and repair are among the fastest in our service area. Climewave Engineers covers Lalkuan and neighboring Bindukhatta for both residential and small commercial cooling.",
    servicesHeading: "Our Services in Lalkuan",
    services: ["Split AC installation & repair", "Central AC for homes and small offices", "Annual Maintenance Contracts (AMC)", "Free site visit & load calculation", "Filter & refrigerant servicing"],
    areasHeading: "Areas We Serve in Lalkuan",
    areas: "Lalkuan, Haldwani, Kathgodam, Bindukhatta",
    whyHeading: "Why Choose Climewave in Lalkuan?",
    why: "Being based near Haldwani means a Lalkuan service call doesn't sit in a queue behind installations happening two hours away — it's part of the same daily route.",
  },
  {
    path: "/hvac-services/kitcha/",
    title: "HVAC Services in Kitcha | AC Installation & Repair | Climewave Engineers",
    description: "AC installation and repair in Kichha (Kitcha), near Rudrapur and Sitarganj. Residential split AC and small commercial cooling systems.",
    h1: "HVAC Services in Kitcha",
    intro: "Kitcha (Kichha) falls within our Rudrapur–Sitarganj corridor coverage, giving residential and small commercial customers here access to the same installation standards we use on larger industrial jobs nearby.",
    servicesHeading: "Our Services in Kitcha",
    services: ["Split AC installation & repair", "Small commercial cooling systems", "Annual Maintenance Contracts (AMC)", "Free load calculation & site visit", "AC gas refilling & compressor repair"],
    areasHeading: "Areas We Serve in Kitcha",
    areas: "Kitcha (Kichha), Rudrapur, Sitarganj, Gadarpur",
    whyHeading: "Why Choose Climewave in Kitcha?",
    why: "Our technicians already service the Rudrapur industrial corridor daily, so a Kitcha installation or repair call gets engineers who work at that scale, not a one-person part-time operation.",
  },
  {
    path: "/hvac-services/dehradun/",
    title: "HVAC Services in Dehradun | AC Installation & Central AC | Climewave Engineers",
    description: "HVAC installation and central AC design in Dehradun — homes, offices and retail. AI-powered BTU calculator, VRF systems, and free site visit.",
    h1: "HVAC Services in Dehradun",
    intro: "Dehradun's mix of hillside bungalows, apartment complexes, and commercial spaces means no two installations look the same. Climewave Engineers extends our Kumaon-built engineering standards to Dehradun, from single-room split AC to full central AC retrofits.",
    servicesHeading: "Our Services in Dehradun",
    services: ["Central AC design & installation", "Split AC for homes and apartments", "VRF/VRV systems for offices & retail", "Energy efficiency audits", "Annual Maintenance Contracts (AMC)"],
    areasHeading: "Areas We Serve in Dehradun",
    areas: "Dehradun, Rajpur Road, Clement Town, Rishikesh Road, Mussoorie Road",
    whyHeading: "Why Choose Climewave in Dehradun?",
    why: "Most Dehradun homes still run 3–4 separate split ACs on separate compressors. Our free calculator shows you, in rupees, what a single central AC system would save on the same square footage before you commit to either approach.",
  },
  {
    path: "/ac-repair/dehradun/",
    title: "AC Repair in Dehradun | Split & Central AC | Climewave Engineers",
    description: "AC repair in Dehradun for split and central AC systems — gas refilling, compressor faults, and AMC servicing. Free diagnosis, fast response.",
    h1: "AC Repair in Dehradun",
    intro: "Whether it's a single split unit in an apartment or a central AC system serving an entire office floor, Climewave Engineers' Dehradun repair team diagnoses the actual fault before recommending a fix — not the other way around.",
    servicesHeading: "Common Repairs We Handle",
    services: ["Split AC gas refilling & compressor repair", "Central AC ductwork & AHU fault diagnosis", "No-cooling & uneven-cooling troubleshooting", "COP performance testing", "AMC renewal & pre-monsoon servicing"],
    areasHeading: "Repair Coverage Area",
    areas: "Dehradun, Rajpur Road, Clement Town, Rishikesh Road",
    whyHeading: "Why Book Repairs Through Climewave?",
    why: "Because we design central AC systems ourselves, our Dehradun repair technicians can diagnose AHU and ductwork issues that a split-AC-only technician typically can't — a common gap in this market.",
  },
];
